# Generated by Django 4.1.3 on 2022-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YambScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(max_length=255)),
                ('player1_score', models.SmallIntegerField()),
                ('player2_name', models.CharField(max_length=255)),
                ('player2_score', models.SmallIntegerField()),
            ],
        ),
    ]
