# Generated by Django 4.1.3 on 2023-01-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_name', to='api.player')),
                ('player1_score', models.ManyToManyField(related_name='player1_score', to='api.score')),
                ('player2_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_name', to='api.player')),
                ('player2_score', models.ManyToManyField(related_name='player2_score', to='api.score')),
            ],
        ),
    ]
